docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.20.1
docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter:v0.20.1
docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.20.1
docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.20.1
docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/nop:v0.20.1
docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter:v0.20.1
docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/pullrequest-init:v0.20.1
docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/vendor/github.com/googlecloudplatform/cloud-builders/gcs-fetcher/cmd/gcs-fetcher:v0.20.1
docker pull gcr.io/google.com/cloudsdktool/cloud-sdk
docker pull gcr.io/distroless/base
docker pull gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.20.1
