{
 "title": "# Dashboard",
 "tags": [
  "dashboard",
  "incoming"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "label": "app", "query": "label_values(up, appId)" }
  ]
 },
 "panels": [
  {
   "title": "HTTP Incoming QPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " sum\n  by(appId) (rate(http_incoming_requests_latency_seconds_histogram_count{appId=~\"$app\"}[3m] offset\n  1m))",
     "legendFormat": "{{appId}}"
    }
   ]
  },
  {
   "title": "HTTP 并发",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum\n  by(appId) (http_incoming_requests_concurrent_gauge{appId=~\"$app\"} offset 1m)",
     "legendFormat": "{{appId}}"
    }
   ]
  },
  {
   "title": "HTTP Incoming P99",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum by(appId, le) (rate(http_incoming_requests_latency_seconds_histogram_bucket{appId=~\"$app\"}[3m])))",
     "legendFormat": "{{appId}}"
    }
   ]
  },
  {
   "title": "Motan Incoming QPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum\n  by(appId) (rate(motan_requests_in_latency_seconds_histogram_count{appId=~\"$app\"}[3m] offset\n  1m))",
     "legendFormat": "{{appId}}"
    }
   ]
  },
  {
   "title": "Motan 并发",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum\n  by(appId) (motan_requests_in_concurrent_gauge{appId=~\"$app\"} offset 1m)",
     "legendFormat": "{{appId}}"
    }
   ]
  },
  {
   "title": "Motan Incoming P99",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum by(appId, le) (rate(motan_requests_in_latency_seconds_histogram_bucket{appId=~\"$app\"}[3m])))",
     "legendFormat": "{{appId}}"
    }
   ]
  },
  {
   "title": "HTTP 4XX/5XX Error - 累计值",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (app)(http_incoming_requests_latency_seconds_histogram_count{status=~\"4..\"})",
     "legendFormat": "{{app}} - 4XX"
    },
    {
     "expr": "sum by (app)(http_incoming_requests_latency_seconds_histogram_count{status=~\"5..\"})",
     "legendFormat": "{{app}} - 5XX"
    }
   ]
  },
  {
   "title": "HTTP Exception - 累计值",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (app)(http_incoming_requests_err_counter{})",
     "legendFormat": "{{app}} "
    }
   ]
  },
  {
   "title": "Motan Incoming Error - 2min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(app) (increase(motan_requests_in_err_counter{appId=~\"$app\"}[2m]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "Motan Outgoing Error - 2min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(app) (increase(motan_requests_out_err_counter{appId=~\"$app\"}[2m]))",
     "legendFormat": "{{app}}"
    }
   ]
  },
  {
   "title": "HTTP Incoming",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": " sum\n  by(appId) (rate(http_incoming_requests_latency_seconds_histogram_count{appId=~\"$app\"}[3m] offset\n  1m))"
    },
    {
     "expr": "sum\n  by(appId) (http_incoming_requests_concurrent_gauge{appId=~\"$app\"} offset 1m)"
    },
    {
     "expr": "histogram_quantile(0.99,\n  sum by(appId, le) (rate(http_incoming_requests_latency_seconds_histogram_bucket{appId=~\"$app\"}[3m])))"
    },
    {
     "expr": "histogram_quantile(0.999,\n  sum by(appId, le) (rate(http_incoming_requests_latency_seconds_histogram_bucket{appId=~\"$app\"}[3m])))"
    }
   ]
  },
  {
   "title": "Motan Incoming",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum\n  by(appId) (rate(motan_requests_in_latency_seconds_histogram_count{appId=~\"$app\"}[3m] offset\n  1m))"
    },
    {
     "expr": "sum\n  by(appId) (motan_requests_in_concurrent_gauge{appId=~\"$app\"} offset 1m)"
    },
    {
     "expr": "histogram_quantile(0.99,\n  sum by(appId, le) (rate(motan_requests_in_latency_seconds_histogram_bucket{appId=~\"$app\"}[3m])))"
    },
    {
     "expr": "histogram_quantile(0.999,\n  sum by(appId, le) (rate(motan_requests_in_latency_seconds_histogram_bucket{appId=~\"$app\"}[3m])))"
    }
   ]
  }
 ]
}