{
 "title": "# Dashboard Internal Metrics",
 "tags": [
  "internal",
  "dashboard"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "label": "app", "query": "label_values(up, appId)" }
  ]
 },
 "panels": [
  {
   "title": "JedisClient / JedisClusterClient",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "QPS - JedisClient / JedisClusterClient",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(namespace) (rate(jedisCluster_latency_seconds_histogram_count{appId=~\"$app\"}[3m]))",
       "legendFormat": "cluster::{{namespace}}"
      },
      {
       "expr": "sum by(namespace) (rate(jedis_latency_seconds_histogram_count{appId=~\"$app\"}[3m]))",
       "legendFormat": "std::{{namespace}}"
      }
     ]
    },
    {
     "title": "并发 - JedisClient / JedisClusterClient",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (jedisCluster_concurrent_gauge{appId=~\"$app\"})",
       "legendFormat": "cluster::{{namespace}}"
      },
      {
       "expr": "sum by (namespace) (jedis_concurrent_gauge{appId=~\"$app\"})",
       "legendFormat": "std::{{namespace}}"
      }
     ]
    },
    {
     "title": "P99 - JedisClient / JedisClusterClient",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99,\n  sum by(namespace, le) (rate(jedisCluster_latency_seconds_histogram_bucket{appId=~\"$app\"}[3m])))",
       "legendFormat": "cluster::{{namespace}}"
      },
      {
       "expr": "histogram_quantile(0.99,\n  sum by(namespace, le) (rate(jedis_latency_seconds_histogram_bucket{appId=~\"$app\"}[3m])))",
       "legendFormat": "std::{{namespace}}"
      }
     ]
    },
    {
     "title": "错误率 - JedisClient / JedisClusterClient",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(((sum\n  by(namespace, operation) (increase(jedisCluster_err_counter{appId=~\"$app\"}[3m]))\n  / sum by(namespace, operation) (increase(jedisCluster_latency_seconds_histogram_count[3m]))) * 100) + 0.00001)> 0.00001",
       "legendFormat": "cluster::{{namespace}}-{{operation}}"
      },
      {
       "expr": "(((sum\n  by(namespace, operation) (increase(jedis_err_counter{appId=~\"$app\"}[3m]))\n  / sum by(namespace, operation) (increase(jedis_latency_seconds_histogram_count[3m]))) * 100) + 0.00001)> 0.00001",
       "legendFormat": "std::{{namespace}}-{{operation}}"
      }
     ]
    },
    {
     "title": "QPS - JedisClient By Method",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(namespace,operation) (rate(jedis_latency_seconds_histogram_count{appId=~\"$app\"}[3m]))",
       "legendFormat": "std::{{namespace}}::{{operation}}"
      }
     ]
    },
    {
     "title": "并发 - JedisClient By Method",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace) (jedis_concurrent_gauge{appId=~\"$app\"})",
       "legendFormat": "std::{{namespace}}"
      }
     ]
    },
    {
     "title": "P99 - JedisClient By Method",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99,\n  sum by(namespace, operation, le) (rate(jedis_latency_seconds_histogram_bucket{appId=~\"$app\"}[3m])))",
       "legendFormat": "std::{{namespace}}::{{operation}}"
      }
     ]
    },
    {
     "title": "错误率 - JedisClient By Method",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(((sum\n  by(namespace, operation) (increase(jedis_err_counter{appId=~\"$app\"}[3m]))\n  / sum by(namespace, operation) (increase(jedis_latency_seconds_histogram_count[3m]))) * 100) + 0.00001)> 0.00001",
       "legendFormat": "std::{{namespace}}-{{operation}}"
      }
     ]
    },
    {
     "title": "QPS - JedisClusterClient By Method",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(namespace,operation) (rate(jedisCluster_latency_seconds_histogram_count{appId=~\"$app\"}[3m]))",
       "legendFormat": "cluster::{{namespace}}::{{operation}}"
      }
     ]
    },
    {
     "title": "并发 - JedisClient / JedisClusterClient",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (namespace,operation) (jedisCluster_concurrent_gauge{appId=~\"$app\"})",
       "legendFormat": "cluster::{{namespace}}::{{operation}}"
      }
     ]
    },
    {
     "title": "P99 - JedisClusterClient By Method",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99,\n  sum by(namespace, operation, le) (rate(jedisCluster_latency_seconds_histogram_bucket{appId=~\"$app\"}[3m])))",
       "legendFormat": "cluster::{{namespace}}::{{operation}}"
      }
     ]
    },
    {
     "title": "错误率 - JedisClusterClient By Method",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(((sum\n  by(namespace, operation) (increase(jedisCluster_err_counter{appId=~\"$app\"}[3m]))\n  / sum by(namespace, operation) (increase(jedisCluster_latency_seconds_histogram_count[3m]))) * 100) + 0.00001)> 0.00001",
       "legendFormat": "cluster::{{namespace}}-{{operation}}"
      }
     ]
    }
   ]
  },
  { "title": "Mapper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "QPS - Mapper",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(class) (rate(mapper_latency_seconds_histogram_count{appId=~\"$app\"}[3m]))",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "并发 - Mapper",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(class) (mapper_concurrent_gauge{appId=~\"$app\"} offset 1m)",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "P99 - Mapper",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(class, le) (rate(mapper_latency_seconds_histogram_bucket{appId=~\"$app\"}[3m])))",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "错误率 - Mapper",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(((sum\n  by(class) (increase(mapper_err_counter{appId=~\"$app\"}[10m]))\n  / sum by(class) (increase(mapper_latency_seconds_histogram_count{appId=~\"$app\"}[10m]))) * 100) + 0.00001) > 0.00001",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "QPS - By Method",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(operation) (rate(mapper_latency_seconds_histogram_count{appId=~\"$app\"}[3m]))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "并发 - By Method",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(operation) (mapper_concurrent_gauge{appId=~\"$app\"} offset 1m)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "P99 - By Method",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(operation, le) (rate(mapper_latency_seconds_histogram_bucket{appId=~\"$app\"}[3m])))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "错误率 - By Method",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(((sum\n  by(operation) (increase(mapper_err_counter{appId=~\"$app\"}[10m]))\n  / sum by(operation) (increase(mapper_latency_seconds_histogram_count{appId=~\"$app\"}[10m]))) * 100) + 0.00001) > 0.00001",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Custom Profiler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "QPS - Profiler",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(operation) (rate(custom_latency_seconds_histogram_count{appId=~\"$app\"}[3m]))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "并发 - Profiler",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by(operation) (custom_concurrent_gauge{appId=~\"$app\"} offset 1m)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "P99 - Profiler",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum by(operation, le) (rate(custom_latency_seconds_histogram_bucket{appId=~\"$app\"}[3m])))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "P999 - Profiler",
     "type": "graph",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum by(operation, le) (rate(custom_latency_seconds_histogram_bucket{appId=~\"$app\"}[3m])))",
       "legendFormat": "{{operation}}"
      }
     ]
    }
   ]
  }
 ]
}