{
 "title": "Incoming / Motan",
 "tags": [
  "motan",
  "incoming"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "label": "app", "query": "label_values(up, appId)" }
  ]
 },
 "panels": [
  {
   "title": "QPS By Method",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(method) (rate(motan_requests_in_latency_seconds_histogram_count{appId=~\"$app\"}[3m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "MAX P99 By Method",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum by(method, le) (rate(motan_requests_in_latency_seconds_histogram_bucket{appId=\"$app\"}[3m])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "并发 By Method",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (motan_requests_in_concurrent_gauge{appId=~\"$app\"} offset 1m ) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "错误率 by Method",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((sum\n  by(method) (increase(motan_requests_in_err_counter{appId=~\"$app\"}[10m]))\n  / sum by(method) (increase(motan_requests_in_latency_seconds_histogram_count{}[10m]))) * 100) + 0.00001 > 0.00001",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "QPS By Instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(motan_requests_in_latency_seconds_histogram_count{appId=~\"$app\"}[3m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "MAX P99 By Instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum by(pod, le) (rate(motan_requests_in_latency_seconds_histogram_bucket{appId=\"$app\"}[3m])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "并发 By Instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (motan_requests_in_concurrent_gauge{appId=~\"$app\"} offset 1m ) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "错误率 by Instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((sum\n  by(pod) (increase(motan_requests_in_err_counter{appId=~\"$app\"}[10m]))\n  / sum by(pod) (increase(motan_requests_in_latency_seconds_histogram_count{}[10m]))) * 100) + 0.00001 > 0.00001",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "请点击服务名进入详情",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(method) (rate(motan_requests_in_latency_seconds_histogram_count{appId=~\"$app\"}[3m]))",
     "legendFormat": "QPS"
    },
    {
     "expr": "((\n  sum by(method) (increase(motan_requests_in_err_counter{appId=~\"$app\"}[10m]))\n  / \n  (sum by(method) (increase(motan_requests_in_latency_seconds_histogram_count{}[10m])) + 0.0001)\n  ) * 100)",
     "legendFormat": "错误率"
    },
    {
     "expr": "histogram_quantile(0.99,\n  sum by(method, le) (rate(motan_requests_in_latency_seconds_histogram_bucket{appId=\"$app\"}[3m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.999,\n  sum by(method, le) (rate(motan_requests_in_latency_seconds_histogram_bucket{appId=\"$app\"}[3m])))",
     "legendFormat": "P999"
    },
    {
     "expr": "sum (motan_requests_in_concurrent_gauge{appId=~\"$app\"} offset 1m ) by (method)",
     "legendFormat": "并发"
    }
   ]
  }
 ]
}