{
 "title": "Incoming / HTTP / Drill",
 "tags": [
  "http",
  "incoming"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "label": "app", "query": "label_values(up, appId)" },
   {
    "name": "url",
    "label": "url",
    "query": "label_values(http_incoming_requests_latency_seconds_histogram_count{appId=\"$app\"}, url)"
   },
   {
    "name": "pod",
    "label": "pod",
    "query": "label_values(http_incoming_requests_max_gauge{appId=\"$app\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "http - $url", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "url" },
  {
   "title": "并发",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (http_incoming_requests_concurrent_gauge{appId=~\"$app\", url=~\"$url\", pod=~\"$pod\"} offset 1m ) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "MAX - $url",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_incoming_requests_max_gauge{app=\"$app\", url=\"$url\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P99 - $url",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 1 },
   "repeat": "motan",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum by(pod, le) (rate(http_incoming_requests_latency_seconds_histogram_bucket{app=\"$app\", url=\"$url\", pod=~\"$pod\"}[3m])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P999 - $url",
   "type": "graph",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999,\n  sum by(pod, le) (rate(http_incoming_requests_latency_seconds_histogram_bucket{app=\"$app\", url=\"$url\", pod=~\"$pod\"}[3m])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(http_incoming_requests_latency_seconds_histogram_count{appId=~\"$app\", url=~\"$url\", pod=~\"$pod\"}[3m])) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "FTL - $url",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "http_incoming_requests_ftl_gauge{app=\"$app\", url=\"$url\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}