{
 "title": "Internal / Sentinel Stats",
 "tags": [ "internal" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "label": "app", "query": "label_values(up, appId)" },
   {
    "name": "name",
    "label": "name",
    "query": "label_values(app_sentinel_metrics{appId=\"$app\"}, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "oneMinute Summary",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_sentinel_metrics{appId=~\"$app\", type=~\"oneMinuteBlock|oneMinuteException|oneMinutePass|oneMinuteTotal\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "QPS Summary",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_sentinel_metrics{appId=~\"$app\", type=~\"blockQps|exceptionQps|passQps|successQps|totalQps\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Http::In", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "blockQps By Instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_sentinel_metrics{type=\"blockQps\", appId=~\"$app\", name=~\"http:in:.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "exceptionQps By Instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_sentinel_metrics{type=\"exceptionQps\", appId=~\"$app\", name=~\"http:in:.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "averageRt By Instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(app_sentinel_metrics{appId=~\"$app\", type=~\"averageRt\", name=~\"http:in:.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "totalQps By Instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_sentinel_metrics{type=\"totalQps\", appId=~\"$app\", name=~\"http:in:.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "passQps By Instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_sentinel_metrics{type=\"passQps\", appId=~\"$app\", name=~\"http:in:.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "successQps By Instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_sentinel_metrics{type=\"successQps\", appId=~\"$app\", name=~\"http:in:.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "blockQps By Name",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_sentinel_metrics{type=\"blockQps\", appId=~\"$app\", name=~\"http:in:.*\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "exceptionQps By Name",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_sentinel_metrics{type=\"exceptionQps\", appId=~\"$app\", name=~\"http:in:.*\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "averageRt By Name",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(app_sentinel_metrics{appId=~\"$app\", type=~\"averageRt\", name=~\"http:in:.*\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "totalQps By Name",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_sentinel_metrics{type=\"totalQps\", appId=~\"$app\", name=~\"http:in:.*\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "passQps By Name",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_sentinel_metrics{type=\"passQps\", appId=~\"$app\", name=~\"http:in:.*\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "successQps By Name",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_sentinel_metrics{type=\"successQps\", appId=~\"$app\", name=~\"http:in:.*\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Http::Bio::Out",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "blockQps By Instance",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(app_sentinel_metrics{type=\"blockQps\", appId=~\"$app\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "exceptionQps By Instance",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(app_sentinel_metrics{type=\"exceptionQps\", appId=~\"$app\", name=~\"Http::Bio::Out\"}) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "averageRt By Instance",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(app_sentinel_metrics{appId=~\"$app\", type=~\"averageRt\", name=~\"Http::Bio::Out\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "totalQps By Instance",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(app_sentinel_metrics{type=\"totalQps\", appId=~\"$app\", name=~\"Http::Bio::Out\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "passQps By Instance",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(app_sentinel_metrics{type=\"passQps\", appId=~\"$app\", name=~\"Http::Bio::Out\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "successQps By Instance",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(app_sentinel_metrics{type=\"successQps\", appId=~\"$app\", name=~\"Http::Bio::Out\"}) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "blockQps By Name",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(app_sentinel_metrics{type=\"blockQps\", appId=~\"$app\", name=~\"CHttpBioClient(.*)\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "exceptionQps By Name",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(app_sentinel_metrics{type=\"exceptionQps\", appId=~\"$app\", name=~\"CHttpBioClient(.*)\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "averageRt By Name",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(app_sentinel_metrics{appId=~\"$app\", type=~\"averageRt\", name=~\"CHttpBioClient(.*)\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "totalQps By Name",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(app_sentinel_metrics{type=\"totalQps\", appId=~\"$app\", name=~\"CHttpBioClient(.*)\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "passQps By Name",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(app_sentinel_metrics{type=\"passQps\", appId=~\"$app\", name=~\"CHttpBioClient(.*)\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "successQps By Name",
     "type": "graph",
     "gridPos": { "h": 5, "w": 4, "x": 20, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(app_sentinel_metrics{type=\"successQps\", appId=~\"$app\", name=~\"CHttpBioClient(.*)\"}) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  { "title": "$name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }, "repeat": "name" },
  {
   "title": "blockQps By Instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_sentinel_metrics{type=\"blockQps\", appId=~\"$app\", name=~\"$name\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "exceptionQps By Instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_sentinel_metrics{type=\"exceptionQps\", appId=~\"$app\", name=~\"$name\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "oneMinute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_sentinel_metrics{appId=~\"$app\", type=~\"oneMinuteBlock|oneMinuteException|oneMinutePass|oneMinuteTotal\", name=~\"$name\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "QPS Summary",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_sentinel_metrics{appId=~\"$app\", type=~\"passQps|successQps|totalQps|exceptionQps|blockQps\", name=~\"$name\"}) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "averageRt By Instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "app_sentinel_metrics{appId=~\"$app\", type=~\"averageRt\", name=~\"$name\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}