{
 "title": "Outcoming / Dubbo",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "label": "app", "query": "label_values(up, appId)" }
  ]
 },
 "panels": [
  {
   "title": "QPS By Method",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(method) (rate(dubbo_requests_out_latency_seconds_histogram_count{appId=~\"$app\"}[3m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "MAX P99 By Method",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum by(method, le) (rate(dubbo_requests_out_latency_seconds_histogram_bucket{appId=\"$app\"}[3m])))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "并发 By Method",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (dubbo_requests_out_concurrent_gauge{appId=~\"$app\"} offset 1m ) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "错误率 by Method",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((sum\n  by(method) (increase(dubbo_requests_out_err_counter{appId=~\"$app\"}[10m]))\n  / sum by(method) (increase(dubbo_requests_out_latency_seconds_histogram_count{}[10m]))) * 100) + 0.00001 > 0.00001",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "QPS By Instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(dubbo_requests_out_latency_seconds_histogram_count{appId=~\"$app\"}[3m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "MAX P99 By Instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum by(pod, le) (rate(dubbo_requests_out_latency_seconds_histogram_bucket{appId=\"$app\"}[3m])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "并发 By Instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (dubbo_requests_out_concurrent_gauge{appId=~\"$app\"} offset 1m ) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "错误率 by Instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((sum\n  by(pod) (increase(dubbo_requests_out_err_counter{appId=~\"$app\"}[10m]))\n  / sum by(pod) (increase(dubbo_requests_out_latency_seconds_histogram_count{}[10m]))) * 100) + 0.00001 > 0.00001",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}