{
 "title": "Outgoing / HTTP / HTTP Bio",
 "tags": [
  "http",
  "outgoing"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "label": "app", "query": "label_values(up, appId)" },
   {
    "name": "route",
    "label": "route",
    "query": "query_result(sum(increase(app_http_bio_outgoing_requests_default_latency_seconds_histogram_count{appId=\"$app\"}[1d])) by (route) > 30) "
   }
  ]
 },
 "panels": [
  { "title": "概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(route) (rate(app_http_bio_outgoing_requests_default_latency_seconds_histogram_count{appId=~\"$app\"}[3m]))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "连接数",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_http_bio_outgoing_conn_default{appId=\"$app\", state!~\"Max|Pending\"}) by (route)",
     "legendFormat": "{{route}} "
    }
   ]
  },
  {
   "title": "并发数",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(chttpbioclient_requests_default_concurrent_gauge{app=\"$app\"}) by (route)",
     "legendFormat": "{{route}} "
    }
   ]
  },
  {
   "title": "错误率",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((sum\n  by(route) (increase(app_http_bio_outgoing_requests_default_err_counter{appId=~\"$app\"}[10m]))\n  / sum by(route) (increase(app_http_bio_outgoing_requests_default_latency_seconds_histogram_count{appId=~\"$app\"}[10m]))) * 100)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  { "title": "$route", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "route" },
  {
   "title": "连接数",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(app_http_bio_outgoing_conn_default{appId=\"$app\", state!~\"Max|Pending\", route=~\"$route\"}) by (pod)",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(app_http_bio_outgoing_requests_default_latency_seconds_histogram_count{appId=~\"$app\", route=~\"$route\"}[3m]))",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "P99 - $route",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pod, le) (rate(app_http_bio_outgoing_requests_default_latency_seconds_histogram_bucket{appId=~\"$app\", route=~\"$route\"}[3m]))) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P999 - $route",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 15, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum by(pod, le) (rate(app_http_bio_outgoing_requests_default_latency_seconds_histogram_bucket{appId=~\"$app\", route=~\"$route\"}[3m]))) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}