{
 "title": "Outgoing / Motan / Drill",
 "tags": [
  "motan",
  "outgoing"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "label": "app", "query": "label_values(up, appId)" },
   {
    "name": "method",
    "label": "method",
    "query": "label_values(motan_requests_out_latency_seconds_histogram_count{appId=\"$app\"}, method)"
   }
  ]
 },
 "panels": [
  { "title": "Motan：Incoming - $method", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "method" },
  {
   "title": "错误数 - 1m",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(motan_requests_out_err_counter{appId=~\"$app\"}[1m]))",
     "legendFormat": "错误数 - 1m"
    }
   ]
  },
  {
   "title": "P99",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 6, "y": 1 },
   "repeat": "motan",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum by(pod, le) (rate(motan_requests_out_latency_seconds_histogram_bucket{appId=\"$app\", method=~\"$method\"}[3m])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P999",
   "type": "graph",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999,\n  sum by(pod, le) (rate(motan_requests_out_latency_seconds_histogram_bucket{appId=\"$app\", method=~\"$method\"}[3m])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "FTL",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "motan_requests_out_ftl{appId=\"$app\", method=~\"$method\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "并发",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "floor(sum (motan_requests_out_concurrent_gauge{appId=~\"$app\", method=~\"$method\"} offset 1m ) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P99对比",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum by(le) (rate(motan_requests_out_latency_seconds_histogram_bucket{appId=\"$app\", method=~\"$method\"}[3m])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.99,\n  sum by(le) (rate(motan_requests_out_latency_seconds_histogram_bucket{appId=\"$app\", method=~\"$method\"}[3m] offset 24h)))",
     "legendFormat": "P99 - Last Day"
    },
    {
     "expr": "histogram_quantile(0.99,\n  sum by(le) (rate(motan_requests_out_latency_seconds_histogram_bucket{appId=\"$app\", method=~\"$method\"}[3m] offset 7d)))",
     "legendFormat": "P99 - Last Week"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(motan_requests_out_latency_seconds_histogram_count{appId=~\"$app\",method=~\"$method\"}[3m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}