{
 "title": "SAF Outgoing / HTTP / HTTPBioClient",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "metrics",
    "label": "metrics",
    "query": "metrics(http_bio_client_outgoing_request_latency_seconds_histogram_count*)"
   },
   {
    "name": "httppool",
    "label": "httppool",
    "query": "label_values($metrics, httppool)"
   },
   { "name": "app", "label": "app", "query": "label_values($metrics, app)" },
   { "name": "host", "label": "host", "query": "label_values($metrics, host)" }
  ]
 },
 "panels": [
  { "title": "概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "QPS by host",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(host) (rate(http_bio_client_outgoing_request_latency_seconds_histogram_count{app=~\"$app\", host=~\"$host\"}[3m]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "P99 by host",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(host, le) (rate(http_bio_client_outgoing_request_latency_seconds_histogram_bucket{app=~\"$app\", host=~\"$host\"}[3m]))) > 0",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "并发数 by host",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_bio_client_outgoing_request_concurrent_gauge{app=~\"$app\", host=~\"$host\"}) by (host)",
     "legendFormat": "{{host}} "
    }
   ]
  },
  {
   "title": "错误率 by host",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((sum\n  by(host) (increase(http_bio_client_outgoing_request_err_counter{app=~\"$app\", host=~\"$host\"}[10m]))\n  / sum by(host) (increase(http_bio_client_outgoing_request_latency_seconds_histogram_count{app=~\"$app\", host=~\"$host\"}[10m]))) * 100)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "QPS by instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(http_bio_client_outgoing_request_latency_seconds_histogram_count{app=~\"$app\", host=~\"$host\"}[3m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P99 by instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pod, le) (rate(http_bio_client_outgoing_request_latency_seconds_histogram_bucket{app=~\"$app\", host=~\"$host\"}[3m]))) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "并发数 by Instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_bio_client_outgoing_request_concurrent_gauge{app=~\"$app\", host=~\"$host\"}) by (pod)",
     "legendFormat": "{{pod}} "
    }
   ]
  },
  {
   "title": "Pending + Leased",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_bio_client_outgoing_connection{app=\"$app\", host=~\"$host\", state!~\"Max|Available\"}) by (pod,state)",
     "legendFormat": "{{pod}}  - {{state}}"
    }
   ]
  },
  {
   "title": "错误率 by Instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((sum\n  by(pod) (increase(http_bio_client_outgoing_request_err_counter{app=~\"$app\", host=~\"$host\"}[3m]))\n  / sum by(pod) (increase(http_bio_client_outgoing_request_latency_seconds_histogram_count{app=~\"$app\", host=~\"$host\"}[3m]))) * 100)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "请点击服务名进入详情",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by(host) (rate(http_bio_client_outgoing_request_latency_seconds_histogram_count{app=~\"$app\"}[3m]))"
    },
    {
     "expr": "sum(http_bio_client_outgoing_request_concurrent_gauge{app=~\"$app\"}) by (host)"
    },
    {
     "expr": "((sum\n  by(host) (increase(http_bio_client_outgoing_request_err_counter{app=~\"$app\"}[10m]))\n  / sum by(host) (increase(http_bio_client_outgoing_request_latency_seconds_histogram_count{app=~\"$app\"}[10m]))) * 100)"
    },
    {
     "expr": "sum(http_bio_client_outgoing_connection{app=\"$app\", state=~\"Leased\"}) by (host)"
    },
    {
     "expr": "sum(http_bio_client_outgoing_connection{app=\"$app\", state=~\"Available\"}) by (host)"
    },
    {
     "expr": "sum(http_bio_client_outgoing_connection{app=\"$app\", state=~\"Pending\"}) by (host)"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(host, le) (rate(http_bio_client_outgoing_request_latency_seconds_histogram_bucket{app=~\"$app\"}[3m]))) > 0"
    },
    {
     "expr": "histogram_quantile(0.999, sum by(host, le) (rate(http_bio_client_outgoing_request_latency_seconds_histogram_bucket{app=~\"$app\"}[3m]))) > 0"
    }
   ]
  },
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }, "repeat": "host" },
  {
   "title": "Conn Stats Pending",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_bio_client_outgoing_connection{app=~\"$app\", host=~\"$host\", state=~\"Pending\"}) by (instance)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "错误率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((sum\n  by(pod) (increase(http_bio_client_outgoing_request_err_counter{app=~\"$app\", host=~\"$host\"}[3m]))\n  / sum by(pod) (increase(http_bio_client_outgoing_request_latency_seconds_histogram_count{app=~\"$app\", host=~\"$host\"}[3m]))) * 100)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(host, pod) (rate(http_bio_client_outgoing_request_latency_seconds_histogram_count{app=~\"$app\", host=~\"$host\"}[3m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P99",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(host, pod, le) (rate(http_bio_client_outgoing_request_latency_seconds_histogram_bucket{app=~\"$app\", host=~\"$host\"}[3m]))) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P999",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum by(host, pod, le) (rate(http_bio_client_outgoing_request_latency_seconds_histogram_bucket{app=~\"$app\", host=~\"$host\"}[3m]))) > 0",
     "legendFormat": "{{pod}} :: {{host}}"
    }
   ]
  },
  {
   "title": "Conn Stats",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_bio_client_outgoing_connection{app=~\"$app\", host=~\"$host\", state!~\"Max\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Conn Stats Pending",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_bio_client_outgoing_connection{app=~\"$app\", host=~\"$host\", state=~\"Pending\"}) by (instance)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "错误率",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((sum\n  by(pod) (increase(http_bio_client_outgoing_request_err_counter{app=~\"$app\", host=~\"$host\"}[3m]))\n  / sum by(pod) (increase(http_bio_client_outgoing_request_latency_seconds_histogram_count{app=~\"$app\", host=~\"$host\"}[3m]))) * 100)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(host, pod) (rate(http_bio_client_outgoing_request_latency_seconds_histogram_count{app=~\"$app\", host=~\"$host\"}[3m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P99",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(host, pod, le) (rate(http_bio_client_outgoing_request_latency_seconds_histogram_bucket{app=~\"$app\", host=~\"$host\"}[3m]))) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P999",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum by(host, pod, le) (rate(http_bio_client_outgoing_request_latency_seconds_histogram_bucket{app=~\"$app\", host=~\"$host\"}[3m]))) > 0",
     "legendFormat": "{{pod}} :: {{host}}"
    }
   ]
  },
  {
   "title": "Conn Stats",
   "type": "graph",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_bio_client_outgoing_connection{app=~\"$app\", host=~\"$host\", state!~\"Max\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}