{
 "title": "SAF Outgoing / HTTP / HTTPBioClient / Detail",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "metrics",
    "label": "metrics",
    "query": "metrics(apache_httpcomponents_bio_client_outgoing_request_latency_seconds_histogram_count*)"
   },
   { "name": "app", "label": "app", "query": "label_values($metrics, app)" },
   { "name": "pod", "label": "pod", "query": "label_values($metrics, pod)" },
   {
    "name": "httppool",
    "label": "httppool",
    "query": "label_values($metrics, httppool)"
   },
   { "name": "host", "label": "host", "query": "label_values($metrics, host)" }
  ]
 },
 "panels": [
  {
   "title": "httppool队列已用容量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apache_httpcomponents_bio_client_outgoing_blocking_queue_used_capacity{app=~\"$app\", pod=~\"$pod\", httppool=~\"$httppool\"}",
     "legendFormat": "{{pod}} :: {{httppool}}"
    }
   ]
  },
  {
   "title": "httppool队列已用容量百分比",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "apache_httpcomponents_bio_client_outgoing_blocking_queue_used_capacity_percentage{app=~\"$app\", pod=~\"$pod\", httppool=~\"$httppool\"}",
     "legendFormat": "{{pod}} :: {{httppool}}"
    }
   ]
  },
  { "title": "${host}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "host" },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(host) (rate(apache_httpcomponents_bio_client_outgoing_request_latency_seconds_histogram_count{app=~\"$app\", pod=~\"$pod\", httppool=~\"$httppool\", host=~\"$host\"}[3m]))",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "连接数",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apache_httpcomponents_bio_client_outgoing_connection{app=~\"$app\", pod=~\"$pod\", httppool=~\"$httppool\", host=~\"$host\", state!~\"Max|Pending\"}) by (host)"
    }
   ]
  },
  {
   "title": "并发数",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(apache_httpcomponents_bio_client_outgoing_request_concurrent_gauge{app=~\"$app\",pod=~\"$pod\", httppool=~\"$httppool\", host=~\"$host\"}) by (host)",
     "legendFormat": "{{host}} "
    }
   ]
  },
  {
   "title": "错误率",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((sum\n  by(host) (increase(apache_httpcomponents_bio_client_outgoing_request_err_counter{app=~\"$app\", pod=~\"$pod\", httppool=~\"$httppool\", host=~\"$host\"}[10m]))\n  / sum by(host) (increase(apache_httpcomponents_bio_client_outgoing_request_latency_seconds_histogram_count{app=~\"$app\", pod=~\"$pod\", httppool=~\"$httppool\", host=~\"$host\"}[10m]))) * 100)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "P99",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pod, le) (rate(apache_httpcomponents_bio_client_outgoing_request_latency_seconds_histogram_bucket{app=~\"$app\", pod=~\"$pod\", httppool=~\"$httppool\", host=~\"$host\"}[3m]))) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "P999",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(pod, le) (rate(apache_httpcomponents_bio_client_outgoing_request_latency_seconds_histogram_bucket{app=~\"$app\", pod=~\"$pod\", httppool=~\"$httppool\", host=~\"$host\"}[3m]))) > 0",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}