{
 "title": "SAF Incoming / HTTP",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "label": "app", "query": "label_values(up, appId)" }
  ]
 },
 "panels": [
  {
   "title": "QPS By URL",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(url,method) (rate(apache_httpcomponents_bio_client_ingoing_request_latency_seconds_histogram_count{app=~\"$app\"}[3m])) >0",
     "legendFormat": "{{url}} :: {{method}}"
    }
   ]
  },
  {
   "title": "MAX P99 By URL",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum by(url, le) (rate(apache_httpcomponents_bio_client_ingoing_request_latency_seconds_histogram_bucket{app=\"$app\"}[3m])))",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "并发 By URL",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (apache_httpcomponents_bio_client_ingoing_request_concurrent_gauge{app=~\"$app\"} offset 1m ) by (url)",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "not 2XX - 1m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (url) (increase(apache_httpcomponents_bio_client_ingoing_request_latency_seconds_histogram_count{app=~\"$app\", status!~\"2..\"}[1m]))",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "QPS By Instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (rate(apache_httpcomponents_bio_client_ingoing_request_latency_seconds_histogram_count{app=~\"$app\"}[3m])) >0",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "MAX P99 By Instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  sum by(pod, le) (rate(apache_httpcomponents_bio_client_ingoing_request_latency_seconds_histogram_bucket{app=\"$app\"}[3m])))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "并发 By Instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(apache_httpcomponents_bio_client_ingoing_request_concurrent_gauge{appId=~\"$app\"} offset 1m ) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "not 2XX By Instance - 1m",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (increase(apache_httpcomponents_bio_client_ingoing_request_latency_seconds_histogram_count{app=~\"$app\", status!~\"2..\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "请点击服务名进入详情",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(url) (rate(apache_httpcomponents_bio_client_ingoing_request_latency_seconds_histogram_count{app=~\"$app\"}[3m])) > 0",
     "legendFormat": "QPS"
    },
    {
     "expr": "((sum\n  by(url) (increase(apache_httpcomponents_bio_client_ingoing_request_err_counter{app=~\"$app\"}[10m]))\n  / sum by(url) (increase(apache_httpcomponents_bio_client_ingoing_request_latency_seconds_histogram_count{app=~\"$app\"}[10m]))) * 100) > 0",
     "legendFormat": "错误率"
    },
    {
     "expr": "histogram_quantile(0.99,\n  sum by(url, le) (rate(apache_httpcomponents_bio_client_ingoing_request_latency_seconds_histogram_bucket{app=\"$app\"}[3m]))) > 0",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.999,\n  sum by(url, le) (rate(apache_httpcomponents_bio_client_ingoing_request_latency_seconds_histogram_bucket{app=\"$app\"}[3m]))) > 0",
     "legendFormat": "P999"
    },
    {
     "expr": "sum (apache_httpcomponents_bio_client_ingoing_request_concurrent_gauge{app=~\"$app\"} offset 1m ) by (url)>0",
     "legendFormat": "并发"
    }
   ]
  }
 ]
}