---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-k8s-0
  labels:
    name: prometheus-k8s
spec:
  accessModes: ["ReadWriteOnce"]
  mountOptions:
      - vers=4.0
      - noresvport
  capacity:
      storage: 100Gi
  storageClassName: "prometheus-k8s"
  persistentVolumeReclaimPolicy: Retain
  #表示使用本地存储
  local:
    path: /datavip/k8s-data/prometheus-k8s-0
  #使用local pv时必须定义nodeAffinity，Kubernetes Scheduler需要使用PV的nodeAffinity描述信息来保证Pod能够调度到有对应local volume的Node上。
  #创建local PV之前，你需要先保证有对应的storageClass已经创建。
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          #future是pod需要分不到的主机名，这台主机上开启了local-pv资源。
          - future
  #生产使用阿里云的nas存储。
  #nfs:
  #  server: aliyun nas url
  #  path: /prometheus-k8s-0

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-k8s-1
  labels:
    name: prometheus-k8s
spec:
  accessModes: ["ReadWriteOnce"]
  mountOptions:
      - vers=4.0
      - noresvport
  capacity:
      storage: 100Gi
  storageClassName: "prometheus-k8s"
  persistentVolumeReclaimPolicy: Retain
  #表示使用本地存储
  local:
    path: /datavip/k8s-data/prometheus-k8s-1
  #使用local pv时必须定义nodeAffinity，Kubernetes Scheduler需要使用PV的nodeAffinity描述信息来保证Pod能够调度到有对应local volume的Node上。
  #创建local PV之前，你需要先保证有对应的storageClass已经创建。
  nodeAffinity:            
    required:              
      nodeSelectorTerms:   
      - matchExpressions:  
        - key: kubernetes.io/hostname
          operator: In     
          values:          
          #future是pod需要分不到的主机名，这台主机上开启了local-pv资源。
          - future         
  #生产使用阿里云的nas存储。
  #nfs:                    
  #  server: aliyun nas url
  #  path: /prometheus-k8s-0
