kubectl apply -f ingress-nginx-apollo-config.yaml
kubectl apply -f ingress-nginx-apollo-portal.yaml
kubectl apply -f ingress-nginx-consul.yaml
#kubectl apply -f ingress-nginx-es-min-kibana.yaml
kubectl apply -f ingress-nginx-es-min.yaml
kubectl apply -f ingress-nginx-gitlab.yaml
#kubectl apply -f ingress-nginx-grafana-k8s.yaml
#kubectl apply -f ingress-nginx-jenkins.yaml
#kubectl apply -f ingress-nginx-nexus.yaml
#kubectl apply -f ingress-nginx-prometheus-k8s.yaml
kubectl apply -f ingress-nginx-rocketmq-min-c0-console.yaml
kubectl apply -f ingress-nginx-skywalking-ui.yaml
#kubectl apply -f ingress-nginx-wayne.yaml
