apiVersion: v1
kind: PersistentVolume
metadata:
  name: consul-min-pv-local
  namespace: consul
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: 'consul-data-pv'
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /datavip/k8s-data/consul-min-pv-local
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - future
