apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-mq-rocketmq
  namespace: monitoring
  labels:
    app: prometheus-mq-rocketmq
data:
  prometheus.yml: >
    global:
      scrape_interval:     60s
      evaluation_interval: 60s

    alerting:
      alertmanagers:
      - static_configs:
        - targets:
		  #定义报警地址
          - alertmanager:9093

	rule_files:
      #- "rocketmq-alert-rule.yaml"

    scrape_configs:

      - job_name: 'rocketmq-monitor'
        kubernetes_sd_configs:
        - role: pod
  
        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_exporter, __meta_kubernetes_namespace]
          action: keep
          regex: rocketmq;monitoring
        - source_labels: [__meta_kubernetes_pod_label_rocketClusterName]
          action: replace
          target_label: rocketmqClusterName
        - source_labels: [__meta_kubernetes_pod_label_namesrvAddr]
          action: replace
          target_label: namesrvAddr

