kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: rabbitmq-wayne
  namespace: wayne
  labels:
    app: rabbitmq-wayne
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-wayne
  template:
    metadata:
      labels:
        app: rabbitmq-wayne
    spec:
      containers:
      - name: rabbitmq
        image: 'rabbitmq:3.7.8-management'
        resources:
          limits:
            cpu: '0.1'
            memory: 1Gi
          requests:
            cpu: '0.1'
            memory: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq-wayne
  name: rabbitmq-wayne
  namespace: wayne
spec:
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: rabbitmq-wayne
