{
 "title": "消息堆积数",
 "tags": [ "rocketmq" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "rocketmqClusterName",
    "label": "rocketmqClusterName",
    "query": "label_values(rocketmq_msg_diff_detail,rocketmqClusterName)"
   },
   {
    "name": "namesrvAddr",
    "label": "namesrvAddr",
    "query": "label_values(rocketmq_msg_diff_detail,namesrvAddr)"
   },
   {
    "name": "topic",
    "label": "topic",
    "query": "label_values(rocketmq_msg_diff_detail, topic)"
   },
   {
    "name": "consumerGroup",
    "label": "consumerGroup",
    "query": "label_values(rocketmq_msg_diff_detail,consumerGroup)"
   },
   {
    "name": "broker",
    "label": "broker",
    "query": "label_values(rocketmq_msg_diff_detail,broker)"
   },
   {
    "name": "queueId",
    "label": "queueId",
    "query": "label_values(rocketmq_msg_diff_detail,queueId)"
   },
   {
    "name": "consumerClientIP",
    "label": "consumerClientIP",
    "query": "label_values(rocketmq_msg_diff_detail,consumerClientIP)"
   },
   {
    "name": "consumerClientPID",
    "label": "consumerClientPID",
    "query": "label_values(rocketmq_msg_diff_detail, consumerClientPID)"
   }
  ]
 },
 "panels": [
  {
   "title": "消息堆积数（消费者进程粒度）；可用筛选条件：全部可用；显示条件：堆积数>1000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_msg_diff_detail{topic=~\"$topic\", consumerGroup=~\"$consumerGroup\", broker=~\"$broker\", queueId=~\"$queueId\", consumerClientIP=~\"$consumerClientIP\", consumerClientPID=~\"$consumerClientPID\", job=\"rocketmq-monitor\", rocketmqClusterName=~\"$rocketmqClusterName\", namesrvAddr=~\"$namesrvAddr\"} > 1000",
     "legendFormat": "{{topic}}::{{consumerGroup}}::{{broker}}::queue-{{queueId}}::{{consumerClientIP}}::{{consumerClientPID}}"
    }
   ]
  },
  {
   "title": "消息堆积数（消费者进程粒度）；可用筛选条件：rocketmqClusterName,  namesrvAddr, consumerClientIP,  consumerClientPID；显示条件：堆积数>1000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_msg_diff_clientinfo{consumerClientIP=~\"$consumerClientIP\", consumerClientPID=~\"$consumerClientPID\", job=\"rocketmq-monitor\", rocketmqClusterName=~\"$rocketmqClusterName\", namesrvAddr=~\"$namesrvAddr\"} > 1000",
     "legendFormat": "{{consumerClientIP}}::{{consumerClientPID}}"
    }
   ]
  },
  {
   "title": "消息堆积数（topic粒度）；可用筛选条件：rocketmqClusterName, namesrvAddr, topic；显示条件：堆积数>1000",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_msg_diff_topic{topic=~\"$topic\", job=\"rocketmq-monitor\", rocketmqClusterName=~\"$rocketmqClusterName\", namesrvAddr=~\"$namesrvAddr\"} > 1000",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "消息堆积数（消费Group粒度）；可用筛选条件：rocketmqClusterName, namesrvAddr, consumerGroup；显示条件：堆积数>1000",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_msg_diff_consumergroup{consumerGroup=~\"$consumerGroup\", job=\"rocketmq-monitor\", rocketmqClusterName=~\"$rocketmqClusterName\", namesrvAddr=~\"$namesrvAddr\"}",
     "legendFormat": "{{consumerGroup}}"
    }
   ]
  },
  {
   "title": "消息堆积数（broker粒度）；可用筛选条件：rocketmqClusterName, namesrvAddr, broker；显示条件：堆积数>1000",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_msg_diff_broker{broker=~\"$broker\", job=\"rocketmq-monitor\", rocketmqClusterName=~\"$rocketmqClusterName\", namesrvAddr=~\"$namesrvAddr\"} > 1000",
     "legendFormat": "{{broker}}"
    }
   ]
  },
  {
   "title": "消息堆积数（queueId粒度）；可用筛选条件：rocketmqClusterName, namesrvAddr, broker, queueId；显示条件：堆积数>1000",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rocketmq_msg_diff_queue{broker=~\"$broker\", queueId=~\"$queueId\", job=\"rocketmq-monitor\", rocketmqClusterName=~\"$rocketmqClusterName\", namesrvAddr=~\"$namesrvAddr\"} > 1000",
     "legendFormat": "{{broker}}::{{queueId}}"
    }
   ]
  }
 ]
}