{
 "title": "Redis / Standard",
 "description": "Prometheus dashboard for Redis servers (by host and alias)",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "alias",
    "label": "alias",
    "query": "label_values(redis_instance_info{redis_mode=\"standalone\"}, alias)"
   },
   {
    "name": "role",
    "label": "role",
    "query": "query_result(redis_instance_info{alias=\"$alias\"}) "
   },
   {
    "name": "host",
    "label": "host",
    "query": "query_result(redis_instance_info{alias=\"$alias\", role=\"$role\", redis_mode=\"standalone\"}) "
   }
  ]
 },
 "panels": [
  { "title": "$role cluster info - bgsave", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rdb Last Bgsave Duration",
   "type": "graph",
   "gridPos": { "h": 12, "w": 9, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "redis_rdb_last_bgsave_duration_sec{alias=\"$alias\", addr=~\"$host\"}",
     "legendFormat": "{{ addr }} "
    }
   ]
  },
  {
   "title": "RDB Last Save Time",
   "type": "table",
   "description": "redis_rdb_last_save_timestamp",
   "gridPos": { "h": 12, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "sum(redis_rdb_last_save_timestamp_seconds{alias=\"$alias\", addr=~\"$host\"} * 1000 + 28800000) by (addr)",
     "legendFormat": "{{addr}}"
    },
    {
     "expr": "sum(redis_rdb_last_bgsave_status{alias=\"$alias\", addr=~\"$host\"}) by (addr)",
     "legendFormat": "{{addr}}"
    },
    {
     "expr": "sum(redis_rdb_last_bgsave_duration_sec{alias=\"$alias\", addr=~\"$host\"}) by (addr)",
     "legendFormat": "{{addr}}"
    },
    {
     "expr": "sum(redis_rdb_last_cow_size_bytes{alias=\"$alias\", addr=~\"$host\"}) by (addr)",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  { "title": "$role - $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "host" },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 14 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{addr=~\"$host\",alias=\"$alias\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_connected_clients{addr=~\"$host\",alias=\"$alias\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (redis_memory_used_bytes{addr=~\"$host\",alias=\"$alias\"}  / redis_memory_max_bytes{addr=~\"$host\",alias=\"$alias\"} )"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(redis_commands_processed_total{addr=~\"$host\",alias=\"$alias\"}[5m]))",
     "legendFormat": "qps"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(irate(redis_keyspace_hits_total{addr=~\"$host\",alias=\"$alias\"}[5m]))",
     "legendFormat": "hits"
    },
    {
     "expr": "avg(irate(redis_keyspace_misses_total{addr=~\"$host\",alias=\"$alias\"}[5m]))",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{addr=~\"$host\",alias=\"$alias\"} ",
     "legendFormat": "used"
    },
    {
     "expr": "redis_memory_max_bytes{addr=~\"$host\",alias=\"$alias\"} ",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{addr=~\"$host\",alias=\"$alias\"}[5m])",
     "legendFormat": "{{ input }}"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{addr=~\"$host\",alias=\"$alias\"}[5m])",
     "legendFormat": "{{ output }}"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{addr=~\"$host\",alias=\"$alias\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{addr=~\"$host\",alias=\"$alias\"}) - sum (redis_db_keys_expiring{addr=~\"$host\",alias=\"$alias\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{addr=~\"$host\",alias=\"$alias\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{addr=~\"$host\",alias=\"$alias\"}[5m])) by (addr)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{addr=~\"$host\",alias=\"$alias\"}[5m])) by (addr)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{addr=~\"$host\",alias=\"$alias\"} [1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  }
 ]
}