{
 "title": "Redis / Cluster",
 "description": "Prometheus dashboard for Redis servers (by host and alias)",
 "tags": [
  "prometheus",
  "redis"
 ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "alias",
    "label": "alias",
    "query": "label_values(redis_instance_info{redis_mode=\"cluster\"}, alias)"
   },
   {
    "name": "role",
    "label": "role",
    "query": "query_result(redis_instance_info{alias=\"$alias\"}) "
   },
   {
    "name": "host",
    "label": "host",
    "query": "query_result(redis_instance_info{alias=\"$alias\", role=\"$role\", redis_mode=\"cluster\"}) "
   }
  ]
 },
 "panels": [
  {
   "title": "$role cluster info - bgsave",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rdb Last Bgsave Duration",
     "type": "graph",
     "gridPos": { "h": 12, "w": 9, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "redis_rdb_last_bgsave_duration_sec{alias=\"$alias\", addr=~\"$host\"}",
       "legendFormat": "{{ addr }} "
      }
     ]
    },
    {
     "title": "RDB Last Save Time",
     "type": "table",
     "description": "redis_rdb_last_save_timestamp",
     "gridPos": { "h": 12, "w": 15, "x": 9, "y": 1 },
     "targets": [
      {
       "expr": "sum(redis_rdb_last_save_timestamp_seconds{alias=\"$alias\", addr=~\"$host\"} * 1000 + 28800000) by (addr)",
       "legendFormat": "{{addr}}"
      },
      {
       "expr": "sum(redis_rdb_last_bgsave_status{alias=\"$alias\", addr=~\"$host\"}) by (addr)",
       "legendFormat": "{{addr}}"
      },
      {
       "expr": "sum(redis_rdb_last_bgsave_duration_sec{alias=\"$alias\", addr=~\"$host\"}) by (addr)",
       "legendFormat": "{{addr}}"
      },
      {
       "expr": "sum(redis_rdb_last_cow_size_bytes{alias=\"$alias\", addr=~\"$host\"}) by (addr)",
       "legendFormat": "{{addr}}"
      }
     ]
    }
   ]
  },
  {
   "title": "$role cluster info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "100 * (sum(redis_memory_used_bytes{alias=\"$alias\", addr=~\"$host\"})  / sum(redis_memory_max_bytes{alias=\"$alias\", addr=~\"$host\"}) )"
      }
     ]
    },
    {
     "title": "Total Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 5, "x": 4, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(redis_memory_used_bytes{alias=\"$alias\", addr=~\"$host\"})",
       "legendFormat": "used"
      },
      {
       "expr": "sum(redis_memory_max_bytes{alias=\"$alias\", addr=~\"$host\"})",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Hits per Sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 9, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (addr) (irate(redis_keyspace_hits_total{alias=\"$alias\", addr=~\"$host\"}[5m]))",
       "legendFormat": "hits-{{addr}}"
      }
     ]
    },
    {
     "title": "Expiring vs Not-Expiring Keys",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (redis_db_keys{alias=\"$alias\", addr=~\"$host\"}) - sum (redis_db_keys_expiring{alias=\"$alias\", addr=~\"$host\"}) ",
       "legendFormat": "not expiring"
      },
      {
       "expr": "sum (redis_db_keys_expiring{alias=\"$alias\", addr=~\"$host\"}) ",
       "legendFormat": "expiring"
      }
     ]
    },
    {
     "title": "Commands Executed / sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (addr) (rate(redis_commands_processed_total{alias=\"$alias\", addr=~\"$host\"}[5m]))",
       "legendFormat": "{{addr}}"
      }
     ]
    },
    {
     "title": "Misses per Sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 9, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (addr)(irate(redis_keyspace_misses_total{alias=\"$alias\", addr=~\"$host\"}[5m]))",
       "legendFormat": "misses-{{addr}}"
      }
     ]
    },
    {
     "title": "Expired / Evicted",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redis_expired_keys_total{alias=\"$alias\", addr=~\"$host\"}[5m])) by (alias)",
       "legendFormat": "expired"
      },
      {
       "expr": "sum(rate(redis_evicted_keys_total{alias=\"$alias\", addr=~\"$host\"}[5m])) by (alias)",
       "legendFormat": "evicted"
      }
     ]
    },
    {
     "title": "Total Items per DB",
     "type": "graph",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum (redis_db_keys{alias=\"$alias\", addr=~\"$host\"}) by (addr)",
       "legendFormat": "{{ addr }} "
      }
     ]
    },
    {
     "title": "Command Calls / sec",
     "type": "graph",
     "gridPos": { "h": 7, "w": 7, "x": 9, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5, sum by (cmd) (irate(redis_commands_total{alias=\"$alias\", addr=~\"$host\"} [1m])))",
       "legendFormat": "{{ cmd }}"
      }
     ]
    },
    {
     "title": "Network I/O",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redis_net_input_bytes_total{alias=\"$alias\", addr=~\"$host\"}[5m]))",
       "legendFormat": "{{ input }}"
      },
      {
       "expr": "sum(rate(redis_net_output_bytes_total{alias=\"$alias\", addr=~\"$host\"}[5m]))",
       "legendFormat": "{{ output }}"
      }
     ]
    }
   ]
  },
  { "title": "node $role - $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 }, "repeat": "host" },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{addr=~\"$host\",alias=\"$alias\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_connected_clients{addr=~\"$host\",alias=\"$alias\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 3 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (redis_memory_used_bytes{addr=~\"$host\",alias=\"$alias\"}  / redis_memory_max_bytes{addr=~\"$host\",alias=\"$alias\"} )"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (addr)(rate(redis_commands_processed_total{addr=~\"$host\",alias=\"$alias\"}[5m]))",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{addr=~\"$host\",alias=\"$alias\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{addr=~\"$host\",alias=\"$alias\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{addr=~\"$host\",alias=\"$alias\"} ",
     "legendFormat": "used"
    },
    {
     "expr": "redis_memory_max_bytes{addr=~\"$host\",alias=\"$alias\"} ",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{addr=~\"$host\",alias=\"$alias\"}[5m])",
     "legendFormat": "{{ input }}"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{addr=~\"$host\",alias=\"$alias\"}[5m])",
     "legendFormat": "{{ output }}"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{addr=~\"$host\",alias=\"$alias\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  {
   "title": "Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "redis_blocked_clients{addr=~\"$host\",alias=\"$alias\"}",
     "legendFormat": "redis_blocked_clients"
    },
    {
     "expr": "redis_connected_clients{addr=~\"$host\",alias=\"$alias\"}",
     "legendFormat": "redis_connected_clients"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{addr=~\"$host\",alias=\"$alias\"}[5m])) by (addr)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{addr=~\"$host\",alias=\"$alias\"}[5m])) by (addr)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{addr=~\"$host\",alias=\"$alias\"}) - sum (redis_db_keys_expiring{addr=~\"$host\",alias=\"$alias\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{addr=~\"$host\",alias=\"$alias\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{addr=~\"$host\",alias=\"$alias\"} [1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  { "title": "node $role - $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 39 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{addr=~\"$host\",alias=\"$alias\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_connected_clients{addr=~\"$host\",alias=\"$alias\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 39 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (redis_memory_used_bytes{addr=~\"$host\",alias=\"$alias\"}  / redis_memory_max_bytes{addr=~\"$host\",alias=\"$alias\"} )"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (addr)(rate(redis_commands_processed_total{addr=~\"$host\",alias=\"$alias\"}[5m]))",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{addr=~\"$host\",alias=\"$alias\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{addr=~\"$host\",alias=\"$alias\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{addr=~\"$host\",alias=\"$alias\"} ",
     "legendFormat": "used"
    },
    {
     "expr": "redis_memory_max_bytes{addr=~\"$host\",alias=\"$alias\"} ",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{addr=~\"$host\",alias=\"$alias\"}[5m])",
     "legendFormat": "{{ input }}"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{addr=~\"$host\",alias=\"$alias\"}[5m])",
     "legendFormat": "{{ output }}"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{addr=~\"$host\",alias=\"$alias\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  {
   "title": "Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "redis_blocked_clients{addr=~\"$host\",alias=\"$alias\"}",
     "legendFormat": "redis_blocked_clients"
    },
    {
     "expr": "redis_connected_clients{addr=~\"$host\",alias=\"$alias\"}",
     "legendFormat": "redis_connected_clients"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{addr=~\"$host\",alias=\"$alias\"}[5m])) by (addr)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{addr=~\"$host\",alias=\"$alias\"}[5m])) by (addr)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{addr=~\"$host\",alias=\"$alias\"}) - sum (redis_db_keys_expiring{addr=~\"$host\",alias=\"$alias\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{addr=~\"$host\",alias=\"$alias\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{addr=~\"$host\",alias=\"$alias\"} [1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  },
  { "title": "node $role - $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 75 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(max_over_time(redis_uptime_in_seconds{addr=~\"$host\",alias=\"$alias\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 2, "y": 75 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "redis_connected_clients{addr=~\"$host\",alias=\"$alias\"}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 75 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100 * (redis_memory_used_bytes{addr=~\"$host\",alias=\"$alias\"}  / redis_memory_max_bytes{addr=~\"$host\",alias=\"$alias\"} )"
    }
   ]
  },
  {
   "title": "Commands Executed / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (addr)(rate(redis_commands_processed_total{addr=~\"$host\",alias=\"$alias\"}[5m]))",
     "legendFormat": "{{addr}}"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{addr=~\"$host\",alias=\"$alias\"}[5m])",
     "legendFormat": "hits"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{addr=~\"$host\",alias=\"$alias\"}[5m])",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Total Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory_used_bytes{addr=~\"$host\",alias=\"$alias\"} ",
     "legendFormat": "used"
    },
    {
     "expr": "redis_memory_max_bytes{addr=~\"$host\",alias=\"$alias\"} ",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(redis_net_input_bytes_total{addr=~\"$host\",alias=\"$alias\"}[5m])",
     "legendFormat": "{{ input }}"
    },
    {
     "expr": "rate(redis_net_output_bytes_total{addr=~\"$host\",alias=\"$alias\"}[5m])",
     "legendFormat": "{{ output }}"
    }
   ]
  },
  {
   "title": "Total Items per DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{addr=~\"$host\",alias=\"$alias\"}) by (db)",
     "legendFormat": "{{ db }} "
    }
   ]
  },
  {
   "title": "Clients",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "redis_blocked_clients{addr=~\"$host\",alias=\"$alias\"}",
     "legendFormat": "redis_blocked_clients"
    },
    {
     "expr": "redis_connected_clients{addr=~\"$host\",alias=\"$alias\"}",
     "legendFormat": "redis_connected_clients"
    }
   ]
  },
  {
   "title": "Expired / Evicted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redis_expired_keys_total{addr=~\"$host\",alias=\"$alias\"}[5m])) by (addr)",
     "legendFormat": "expired"
    },
    {
     "expr": "sum(rate(redis_evicted_keys_total{addr=~\"$host\",alias=\"$alias\"}[5m])) by (addr)",
     "legendFormat": "evicted"
    }
   ]
  },
  {
   "title": "Expiring vs Not-Expiring Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (redis_db_keys{addr=~\"$host\",alias=\"$alias\"}) - sum (redis_db_keys_expiring{addr=~\"$host\",alias=\"$alias\"}) ",
     "legendFormat": "not expiring"
    },
    {
     "expr": "sum (redis_db_keys_expiring{addr=~\"$host\",alias=\"$alias\"}) ",
     "legendFormat": "expiring"
    }
   ]
  },
  {
   "title": "Command Calls / sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 103 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(5, irate(redis_commands_total{addr=~\"$host\",alias=\"$alias\"} [1m]))",
     "legendFormat": "{{ cmd }}"
    }
   ]
  }
 ]
}