mkdir -p /datavip/k8s-data/consul-min-pv-local
mkdir -p /datavip/k8s-data/es-min-ingest0-pv-local
mkdir -p /datavip/k8s-data/pv-metrics-aggregator-promethues/prometheus/data
mkdir -p /datavip/k8s-data/rocketmq-min-c0-broker-master0-pv-local
mkdir -p /datavip/k8s-data/data-redis-ha-min-0
mkdir -p /datavip/k8s-data/es-min-master0-pv-local
mkdir -p /datavip/k8s-data/pv-metrics-alertmanager/prometheus/data
mkdir -p /datavip/k8s-data/rocketmq-min-c0-broker-slave0-pv-local
mkdir -p /datavip/k8s-data/data-redis-ha-min-1
mkdir -p /datavip/k8s-data/gitlab-pv-local
mkdir -p /datavip/k8s-data/pv-metrics-app-grafana
mkdir -p /datavip/k8s-data/slave-jnlp-pv-local
mkdir -p /datavip/k8s-data/data-redis-ha-min-2
mkdir -p /datavip/k8s-data/jenkins-pv-local
mkdir -p /datavip/k8s-data/pv-metrics-app-promethues/prometheus/data
mkdir -p /datavip/k8s-data/zookeeper-min-data0-pv-local
mkdir -p /datavip/k8s-data/data-redis-min-0   
mkdir -p /datavip/k8s-data/mysql-min-pv-local 
mkdir -p /datavip/k8s-data/pv-metrics-exporter-promethues/prometheus/data
mkdir -p /datavip/k8s-data/zookeeper-min-data1-pv-local
mkdir -p /datavip/k8s-data/data-redis-min-1   
mkdir -p /datavip/k8s-data/passport-rpc-impl  
mkdir -p /datavip/k8s-data/pv-metrics-nginx-promethues/prometheus/data
mkdir -p /datavip/k8s-data/zookeeper-min-data2-pv-local
mkdir -p /datavip/k8s-data/data-redis-min-2   
mkdir -p /datavip/k8s-data/passport-web       
mkdir -p /datavip/k8s-data/redis-pv-local     
mkdir -p /datavip/k8s-data/es-min-data0-pv-local             
mkdir -p /datavip/k8s-data/postgres-pv-local  
mkdir -p /datavip/k8s-data/repo-nexus-pv-local

mkdir -p /datavip/k8s-data/data-redis-min-5
mkdir -p /datavip/k8s-data/data-redis-min-4
mkdir -p /datavip/k8s-data/data-redis-min-3
mkdir -p /datavip/k8s-data/data-redis-min-2
mkdir -p /datavip/k8s-data/data-redis-min-1
mkdir -p /datavip/k8s-data/data-redis-min-0

